### ISSUE TITLE
Typos in readme

### ISSUE THREAD

**Issue by kspham** [compbio-UofT/alu-detect#1]
Thanks Mike & Matei for developing this. 
Seems that the read me is not correct in 3.3, instead of ./alu-detect setup, it should be ./alu-detect add-ref 
?
Thanks,
## 3.3. Setup a reference

For this step you need: the reference fasta file, bowtie2 indexes for that
reference, and repeat annotations for that reference. Run, e.g.:

$ ./alu-detect setup hg18

This will ask for: the reference fasta file, the prefix of the bowtie2 index
files (full path minus the .1.bt2 suffix), and a bash regexp (can use wildcards)
describing the path to the relevant .out files output by RepeatMasker.

The paths can also be specified on the command line. Type only

$ ./alu-detect setup

for a list of command line options. E.g.:

$ ./alu-detect setup \
    -f /data/hg18.fa \
    -x /data/bowtie2-index/hg18 \
    -o "/tmp/RepeatMasker-hg18/chr*out" \
    hg18

**Comment by mateidavid** [comment]
Fixed, thanks!
